/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminPagesIndexRouteImport } from './routes/_authenticated/admin/pages/index'
import { Route as AuthenticatedAdminPagesNewRouteImport } from './routes/_authenticated/admin/pages/new'
import { Route as AuthenticatedAdminPagesIdEditRouteImport } from './routes/_authenticated/admin/pages/$id/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminPagesIndexRoute =
  AuthenticatedAdminPagesIndexRouteImport.update({
    id: '/admin/pages/',
    path: '/admin/pages/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPagesNewRoute =
  AuthenticatedAdminPagesNewRouteImport.update({
    id: '/admin/pages/new',
    path: '/admin/pages/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPagesIdEditRoute =
  AuthenticatedAdminPagesIdEditRouteImport.update({
    id: '/admin/pages/$id/edit',
    path: '/admin/pages/$id/edit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/login': typeof LoginRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/admin/pages/new': typeof AuthenticatedAdminPagesNewRoute
  '/admin/pages/': typeof AuthenticatedAdminPagesIndexRoute
  '/admin/pages/$id/edit': typeof AuthenticatedAdminPagesIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/admin/pages/new': typeof AuthenticatedAdminPagesNewRoute
  '/admin/pages': typeof AuthenticatedAdminPagesIndexRoute
  '/admin/pages/$id/edit': typeof AuthenticatedAdminPagesIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/admin/pages/new': typeof AuthenticatedAdminPagesNewRoute
  '/_authenticated/admin/pages/': typeof AuthenticatedAdminPagesIndexRoute
  '/_authenticated/admin/pages/$id/edit': typeof AuthenticatedAdminPagesIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/login'
    | '/admin/'
    | '/admin/pages/new'
    | '/admin/pages/'
    | '/admin/pages/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/login'
    | '/admin'
    | '/admin/pages/new'
    | '/admin/pages'
    | '/admin/pages/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin/'
    | '/_authenticated/admin/pages/new'
    | '/_authenticated/admin/pages/'
    | '/_authenticated/admin/pages/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/pages/': {
      id: '/_authenticated/admin/pages/'
      path: '/admin/pages'
      fullPath: '/admin/pages/'
      preLoaderRoute: typeof AuthenticatedAdminPagesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/pages/new': {
      id: '/_authenticated/admin/pages/new'
      path: '/admin/pages/new'
      fullPath: '/admin/pages/new'
      preLoaderRoute: typeof AuthenticatedAdminPagesNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/pages/$id/edit': {
      id: '/_authenticated/admin/pages/$id/edit'
      path: '/admin/pages/$id/edit'
      fullPath: '/admin/pages/$id/edit'
      preLoaderRoute: typeof AuthenticatedAdminPagesIdEditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminPagesNewRoute: typeof AuthenticatedAdminPagesNewRoute
  AuthenticatedAdminPagesIndexRoute: typeof AuthenticatedAdminPagesIndexRoute
  AuthenticatedAdminPagesIdEditRoute: typeof AuthenticatedAdminPagesIdEditRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminPagesNewRoute: AuthenticatedAdminPagesNewRoute,
  AuthenticatedAdminPagesIndexRoute: AuthenticatedAdminPagesIndexRoute,
  AuthenticatedAdminPagesIdEditRoute: AuthenticatedAdminPagesIdEditRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
